import { useState } from "react";
import { CalendarPlus, Clock3, X } from "lucide-react";
import { PatientCard, PatientPageShell, PatientStatus, usePatientStorage } from "./PatientPageShell";

export default function AppointmentsPage() {
  const [appointments, setAppointments] = usePatientStorage("appointments", [{ id: "APT-001", doctor: "Dr. Adhikari", department: "Cardiology", date: "2026-10-02", time: "09:00", payment: "Pending" }]);
  const [, setInvoices] = usePatientStorage("invoices", [{ id: "INV-001", description: "Cardiology consultation", date: "20 Aug 2026", amount: 1500, status: "Pending" }]);
  const [form, setForm] = useState({ patientType: "old", doctor: "Dr. Adhikari", department: "General Medicine", date: "", time: "" });
  const bookAppointment = (event) => { event.preventDefault(); const fee = form.patientType === "new" ? 1500 : 1000; const id = Date.now(); setAppointments([...appointments, { ...form, id: `APT-${id}`, fee, payment: "Pending" }]); setInvoices((items) => [...items, { id: `INV-${id}`, description: `${form.doctor} consultation`, date: form.date, amount: fee, status: "Pending" }]); setForm({ ...form, date: "", time: "" }); };
  return <PatientPageShell title="Appointments" description="Schedule a visit, see upcoming care, and keep your day organized.">
    <PatientCard title="Book a consultation" description="Choose the visit type first so we can show the correct consultation fee." action={<CalendarPlus className="size-5 text-[#2e7c67]" />}>
      <form onSubmit={bookAppointment} className="space-y-5"><div className="grid gap-3 md:grid-cols-2">{[{ value: "new", label: "New patient", text: "First visit to HILMS", fee: "Rs. 1,500" }, { value: "old", label: "Existing patient", text: "Returning for follow-up", fee: "Rs. 1,000" }].map((option) => <label key={option.value} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-4 transition ${form.patientType === option.value ? "border-[#2e7c67] bg-[#f1faf5] ring-2 ring-[#2e7c67]/10" : "border-[#eadfd5] hover:border-[#b8cfc4]"}`}><input type="radio" name="patientType" value={option.value} checked={form.patientType === option.value} onChange={(e) => setForm({ ...form, patientType: e.target.value })} /><span className="flex-1"><span className="block font-bold text-[#25332e]">{option.label}</span><span className="block text-xs text-[#718079]">{option.text}</span></span><span className="text-sm font-bold text-[#2e7c67]">{option.fee}</span></label>)}</div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-bold text-[#25332e]">Doctor<select className="mt-2 h-11 w-full rounded-xl border border-[#eadfd5] bg-white px-3 text-sm font-normal outline-none focus:border-[#2e7c67]" value={form.doctor} onChange={(e) => setForm({ ...form, doctor: e.target.value })}><option>Dr. Adhikari</option><option>Dr. Sharma</option><option>Dr. Gurung</option></select></label><label className="text-sm font-bold text-[#25332e]">Department<input className="mt-2 h-11 w-full rounded-xl border border-[#eadfd5] bg-white px-3 text-sm font-normal outline-none focus:border-[#2e7c67]" value={form.department} onChange={(e) => setForm({ ...form, department: e.target.value })} /></label><label className="text-sm font-bold text-[#25332e]">Date<input required type="date" className="mt-2 h-11 w-full rounded-xl border border-[#eadfd5] bg-white px-3 text-sm font-normal outline-none focus:border-[#2e7c67]" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} /></label><label className="text-sm font-bold text-[#25332e]">Time<input required type="time" className="mt-2 h-11 w-full rounded-xl border border-[#eadfd5] bg-white px-3 text-sm font-normal outline-none focus:border-[#2e7c67]" value={form.time} onChange={(e) => setForm({ ...form, time: e.target.value })} /></label></div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-[#f0e8e0] pt-4"><p className="text-xs text-[#718079]">A pending invoice will be created after booking.</p><button className="rounded-xl bg-[#1f4a40] px-5 py-2.5 text-sm font-bold text-white transition hover:bg-[#2e7c67]">Confirm appointment</button></div></form>
    </PatientCard>
    <PatientCard title="Upcoming visits" description={`${appointments.length} appointment${appointments.length === 1 ? "" : "s"} scheduled.`}><div className="space-y-3">{appointments.map((appointment) => <div key={appointment.id} className="flex flex-col gap-4 rounded-xl border border-[#eadfd5] p-4 sm:flex-row sm:items-center"><div className="flex size-12 items-center justify-center rounded-xl bg-[#e7f4ee] text-[#1f4a40]"><Clock3 className="size-5" /></div><div className="flex-1"><p className="font-bold text-[#25332e]">{appointment.doctor}</p><p className="text-sm text-[#718079]">{appointment.department} · {appointment.date} at {appointment.time}</p></div><PatientStatus tone={appointment.payment === "Paid" ? "success" : "warning"}>{appointment.payment || "Pending"}</PatientStatus><button aria-label={`Cancel appointment with ${appointment.doctor}`} onClick={() => setAppointments(appointments.filter((item) => item.id !== appointment.id))} className="rounded-lg p-2 text-[#718079] hover:bg-[#fff0eb] hover:text-[#c65743]"><X className="size-4" /></button></div>)}</div></PatientCard>
  </PatientPageShell>;
}
