const mongoose = require("mongoose");
const { ADMIN_APPROVAL_ROLES, getRoleLabel } = require("../config/roles");

const ACCESS_REQUEST_STATUSES = ["PENDING", "APPROVED", "REJECTED"];

/**
 * A public "Request Access" submission by a Doctor or Laboratory applicant.
 *
 * This is NOT a user account and it carries NO credentials at all. Unlike the
 * previous design the applicant never chooses a password: the plaintext
 * temporary password is generated by the backend at approval time, emailed
 * once, and only its bcrypt hash is ever stored. No JWT is issued at any point
 * before an Admin approves the request.
 */
const accessRequestSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: [true, "Applicant name is required"],
      trim: true,
      minlength: [2, "Name must be at least 2 characters"],
      maxlength: [120, "Name must be at most 120 characters"],
    },
    email: {
      type: String,
      required: [true, "Applicant email is required"],
      lowercase: true,
      trim: true,
      // TLD 2-63 characters, the real DNS limit (see the User model).
      match: [/^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,63})+$/, "Please enter a valid email"],
    },
    contactNumber: {
      type: String,
      required: [true, "Contact number is required"],
      trim: true,
    },
    address: {
      type: String,
      required: [true, "Address is required"],
      trim: true,
      maxlength: [300, "Address must be at most 300 characters"],
    },
    requestedRole: {
      type: String,
      // Doctor and Laboratory only. Patients self-register into a real account
      // and therefore never produce an access request (SRS 2.6 / FR-AUTH-02).
      enum: ADMIN_APPROVAL_ROLES,
      required: true,
    },
    // Doctor-only. Never persisted for a Laboratory request.
    nmcNumber: {
      type: String,
      trim: true,
      uppercase: true,
    },
    // Laboratory-only. Never persisted for a Doctor request.
    labRegistryNumber: {
      type: String,
      trim: true,
      uppercase: true,
    },
    status: {
      type: String,
      enum: ACCESS_REQUEST_STATUSES,
      default: "PENDING",
      index: true,
    },
    // Set once the request has been actioned by an administrator.
    reviewedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    reviewedAt: { type: Date },
    reviewNotes: { type: String, trim: true, maxlength: [500, "Review notes must be at most 500 characters"] },
    // Why an Admin declined the request. Kept on the record so the history
    // explains itself; the request is never deleted.
    rejectionReason: { type: String, trim: true, maxlength: [500, "Rejection reason must be at most 500 characters"] },
    // The user account created on approval.
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    userCreatedOnApproval: { type: Boolean, default: false },
  },
  { timestamps: true }
);

// Supports the admin list screen (filter by status, newest first).
accessRequestSchema.index({ status: 1, createdAt: -1 });
accessRequestSchema.index({ requestedRole: 1, status: 1 });

// At most one open request per email address. Declined/approved history is
// kept, so the partial filter is scoped to PENDING only.
accessRequestSchema.index(
  { email: 1 },
  { unique: true, partialFilterExpression: { status: "PENDING" }, name: "one_pending_request_per_email" }
);

// A registration number under review must not already be in use by another open
// request. `sparse` stops the many requests that carry no number colliding.
accessRequestSchema.index(
  { nmcNumber: 1 },
  { unique: true, sparse: true, partialFilterExpression: { status: "PENDING" }, name: "one_pending_nmc_request" }
);
accessRequestSchema.index(
  { labRegistryNumber: 1 },
  { unique: true, sparse: true, partialFilterExpression: { status: "PENDING" }, name: "one_pending_lab_registry_request" }
);

accessRequestSchema.virtual("requestedRoleLabel").get(function () {
  return getRoleLabel(this.requestedRole);
});

const AccessRequest = mongoose.model("AccessRequest", accessRequestSchema);

const toSafeObject = (request) => {
  if (!request) return null;
  const raw = typeof request.toObject === "function" ? request.toObject() : { ...request };
  delete raw.__v;
  return {
    ...raw,
    id: raw._id ? raw._id.toString() : raw.id,
    requestedRoleLabel: getRoleLabel(raw.requestedRole),
    // SRS-facing aliases. `requestedAt` is the submission time (Mongoose records
    // it as `createdAt`) and `createdUserId` is the account made on approval.
    requestedAt: raw.requestedAt || raw.createdAt || null,
    createdUserId: raw.user ? raw.user.toString() : null,
  };
};

module.exports = AccessRequest;
module.exports.ACCESS_REQUEST_STATUSES = ACCESS_REQUEST_STATUSES;
module.exports.toSafeObject = toSafeObject;
